module.exports = {
  "ua": {
    CHOOSE_LANGUAGE_TEXT: 'Choose your language pls',
    LANGUAGE_IS_CHOSEN: 'Ви успішно змінили мову на українську',
    AUTHOR: 'Всі питання до нього: @walterum',
    COMMANDS: '/start - Привітання\n/author - розробник бота\n/commands - опис всіх команд бота\n/about - що може цей бот\n/language - змінити мову',
    UNKNOWN_ERROR: 'Невідома помилка, перевірте правильність посилання, або спробуйте трохи пізніше. Наші адміни уже повідомлені про помилку',
    FILE_IS_TOO_BIG: 'Нажаль, телеграм не дозволяє оброблювати відео, які важать більше ніж 20 мегабайт, раджу вам скинути відео нищої якості або кинути посилання з YouTube',
    DOWNLOADING_VIDEO: 'Скачую відео на сервер',
    CONVERTING_VIDEO: 'Відео скачано, йду його обробляти!',
    SENDING_AUDIO: 'Накінець-то обробив, відсилаю аудіо...',
    IS_NOT_URL: 'Я приймаю тільки відео або посилання, детальніше тут: /about',
    ABOUT: 'Я бот, який конвертує відео в музику, ти можеш кинути мені посилання на ютуб, тікток і я відправлю тобі це відео в аудіоформаті, також ти можеш мені скинути саме відео, але при умові, що воно важить не більше 20-ти мегабайт (обмеження телеграма)',
  },
  "ru": {
    CHOOSE_LANGUAGE_TEXT: 'Choose your language pls',
    LANGUAGE_IS_CHOSEN: 'Ты успешно сменил(-а) язык на русский!',
    AUTHOR: 'Если чё, все вопросы задавать ему: @walterum',
    COMMANDS: '/start - Приветствие\n/author - разработчик бота\n/commands - описание всех команд бота\n/about - что умеет этот бот\n/language - сменить язык',
    UNKNOWN_ERROR: 'Неопознанная ошибка, проверьте правильность ссылки или попробуйте ее скинуть немного позднее, наши админы уже уведомлены об ошибке',
    FILE_IS_TOO_BIG: 'К сожалению, телеграм не позволяет обрабатывать видео, которые весят больше 20-ти мегабайт, советую тебе скинуть видео меньшего качества или скинуть ссылку на YouTube',
    DOWNLOADING_VIDEO: 'Подожди, скачиваю твоё видео на сервер перед обработкой',
    CONVERTING_VIDEO: 'Всё, скачал, иду его обрабатывать...',
    SENDING_AUDIO: 'Уже обработал, скидываю тебе аудио',
    IS_NOT_URL: 'Я принимаю только видео или ссылки, подробнее здесь: /about',
    ABOUT: 'Я бот, который конвертирует видео в музыку, ты можешь кинуть мне ссылку на ютуб, тикток и я отправлю тебе это видео в аудиоформате, также можешь мне кинуть и само видео, но при условии, что оно весит не более 20 мегабайт (ограничение телеграмма)',
  },
  "en": {
    CHOOSE_LANGUAGE_TEXT: 'Choose your language pls',
    LANGUAGE_IS_CHOSEN: 'You successfully changed to English language!',
    AUTHOR: 'All questions to him: @walterum',
    COMMANDS: '/start - Greeting\n/author - bot developer\n/commands - \n/about - description of all bot commands\n/language - Change language',
    UNKNOWN_ERROR: 'Unidentified error, check the link is correct or try to upload it a little later, our admins have already been notified about the error',
    FILE_IS_TOO_BIG: 'Unfortunately, telegram does not allow processing videos that weigh more than 20 megabytes, I advise you to upload a video of lower quality or drop a link to YouTube or TikTok',
    DOWNLOADING_VIDEO: 'Wait, I\'m downloading your video to the server before processing',
    CONVERTING_VIDEO: 'That\'s it, I downloaded it, I\'m going to process it ...',
    SENDING_AUDIO: 'Already processed, I send you the audio',
    IS_NOT_URL: 'I only accept videos or links, more details here: /about',
    ABOUT: 'I am a bot that converts video to music, you can send me a link to YouTube, tiktok and I will send you this video in audio format, you can also send me the video itself, but on condition that it weighs no more than 20 megabytes (telegram limit)',
  },
  "cn": {
    CHOOSE_LANGUAGE_TEXT: '请选择您的语言',
    LANGUAGE_IS_CHOSEN: '您已成功更改为中文！',
    AUTHOR: '对他的所有问题：@walterum',
    COMMANDS: '/start - 问候\n/author - 机器人开发者\n/commands -所有机器人命令的描述 \n/about - 这个机器人能做什么\n/language - 改变语言',
    UNKNOWN_ERROR: '未识别的错误，检查链接是否正确或稍后尝试上传，我们的管理员已收到有关错误的通知',
    FILE_IS_TOO_BIG: '不幸的是，电报不允许处理重量超过 20 兆字节的视频，我建议您上传质量较低的视频或删除 YouTube 的链接',
    DOWNLOADING_VIDEO: '稍等，我正在将您的视频下载到服务器，然后再进行处理',
    CONVERTING_VIDEO: '就是这样，我下载了它，我要处理它......',
    SENDING_AUDIO: '已经处理好了，我把音频发给你',
    IS_NOT_URL: '我只接受视频或链接，更多细节在这里： /about',
    ABOUT: '我是一个将视频转换为音乐的机器人，你可以给我发一个YouTube链接，tiktok，我会发给你音频格式的视频，你也可以把视频本身发给我，但条件是它的重量不超过20 兆字节（电报限制）',
  },
}
